# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


from .ListCapacityHandler import ListCapacityHandler
from .RegisterCapacityHandler import RegisterCapacityHandler
from .GetCapacityHandler import GetCapacityHandler
from .UpdateReservedCapacityHandler import UpdateReservedCapacityHandler
from .UpdateActualUsedCapacityHandler import UpdateActualUsedCapacityHandler
from .RegisterFarmerHandler import RegisterFarmerHandler
from .UpdateFarmerHandler import UpdateFarmerHandler
from .ListFarmersHandler import ListFarmersHandler
from .GetFarmerHandler import GetFarmerHandler
