
User:
  displayName: User
  type: object
  properties:
    id:
      required: false
      displayName: id
      description: int
      type: number
      format: double
    name:
      required: true
      displayName: name
      description: name
      type: string

Group:
  displayName: Group
  type: object
  properties:
    id:
      required: false
      displayName: id
      description: int
      type: number
      format: double
    name:
      required: true
      displayName: name
      description: name
      type: string
