from .client import Client
from js9 import j

class GiteaFactory:

    def __init__(self):
        self.__jslocation__ = "j.clients.gitea"
        self.logger = j.logger.get("j.clients.gitea")

    def get_client(self, base_url, token=None):
        """"
        Get to the autogenerated client for the Gitea RESTful API

        Args:
            ...
        """
        return Client(base_url, token)