
from js9 import j


class ZeroHubClient:
    """
    wrap the autogenerated client for zerohub,
    make userfriendly how to use

    show how to use IYO authentication

    """

    def __init__(self, ...):
        ...

    def sandbox_upload(self, path):
        """
        use sandboxer in jumpscale, to create clean destination with all libs inside
        upload this to hub in most performant & efficient manner

        all what people need to do this action should be called from this method

        """
