# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .Capacity import Capacity
from .Error import Error
from .Farmer import Farmer
from .Location import Location

from .apifarmers_service import ApifarmersService
from .apinodes_service import ApinodesService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri=""):
        http_client = HTTPClient(base_uri)
        self.apifarmers = ApifarmersService(http_client)
        self.apinodes = ApinodesService(http_client)
        self.close = http_client.close
