
generate:
	cp api_spec/main.raml JumpScale9Zrobot/clients/zerorobot/api_spec/main.raml
	go-raml client --language python --dir JumpScale9Zrobot/clients/zerorobot/client --ramlfile api_spec/main.raml --kind requests --python-unmarshall-response