matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      before_install:
        - sudo apt-get install -y python3.5 python3.5-dev
        - sudo rm -f /usr/bin/python
        - sudo rm -f /usr/bin/python3
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python3


      install:
        - curl -s https://install.zerotier.com/ | sudo bash
        - sudo zerotier-cli join ${env_zt_network}
        - sudo ./tests/integration_tests/travis/jumspcale_install.sh ${JSBRANCH}
        - sudo pip3 install -r tests/integration_tests/requirements.txt

      before_script:
        - sudo python3 tests/integration_tests/travis/farm_setup.py --js_flag ${js_flag} --zos_ip ${ZOS_IP} --branch ${JSBRANCH} --zt_token ${zerotier_token} --ubuntu_port ${ubuntu_port}
        - travis_wait 30 sudo ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${ubuntu_port} root@${ZOS_IP} "cd sal_tests/jumpscale_lib; sudo bash tests/integration_tests/travis/jumspcale_install.sh  ${js_flag} "


      script:
        - sudo ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${ubuntu_port} root@${ZOS_IP} "cd sal_tests/jumpscale_lib/tests/integration_tests; nosetests -v -s ${tests_path} --tc-file config.ini"
      after_script:
        - zerotier-cli leave ${env_zt_network}


    - language: python
      sudo: enabled
      dist: trusty
      group: edge

      # whitelist master/development branch only
      branches:
        only:
          - master
          - development

      python:
        - "3.5"

      before_install:
        - sudo apt-get install -y python3.5 python3.5-dev
        - sudo rm -f /usr/bin/python
        - sudo rm -f /usr/bin/python3
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python3

      install: sudo ./.travis_ci/prepare.sh

      before_script:
        - sudo pip3 install pytest 

      script: sudo ./run_tests.sh
