# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from .Action import Action
from .Blueprint import Blueprint
from .Eco import Eco
from .EnumServiceStateState import EnumServiceStateState
from .EnumTaskState import EnumTaskState
from .Error import Error
from .Service import Service
from .ServiceCreate import ServiceCreate
from .ServiceFilter import ServiceFilter
from .ServiceState import ServiceState
from .ServiceUpgradeRequest import ServiceUpgradeRequest
from .Task import Task
from .TaskCreate import TaskCreate
from .Template import Template
from .TemplateRepository import TemplateRepository

from .blueprints_service import BlueprintsService
from .services_service import ServicesService
from .templates_service import TemplatesService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri=""):
        http_client = HTTPClient(base_uri)
        self.blueprints = BlueprintsService(http_client)
        self.services = ServicesService(http_client)
        self.templates = TemplatesService(http_client)
        self.close = http_client.close
