# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumServiceStateState(Enum):
    ok = "ok"
    error = "error"
    warning = "warning"
    skipped = "skipped"
