# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from enum import Enum


class EnumTaskState(Enum):
    new = "new"
    ok = "ok"
    running = "running"
    error = "error"
