# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from js9 import j
JSBASE = j.application.jsbase_get_class()


class UnmarshallError(Exception, JSBASE):
    def __init__(self, resp, message=''):
        JSBASE.__init__(self)
        self.response = resp
        self.message = message
