"""
Holds constants values
"""

HASH_SIZE = 32
MINER_PAYOUT_MATURITY_WINDOW = 144
ADDRESS_TYPE_SIZE = 2
WALLET_ADDRESS_TYPE = bytearray([1])
SWAP_ADDRESS_TYPE = bytearray([2])
HASTINGS_TFT_VALUE = 1000000000
MINIMUM_TRANSACTION_FEE = 1 * HASTINGS_TFT_VALUE
ATOMICSWAP_SECRET_SIZE = 32
