"""
Holds constants values
"""

SIGEd25519 = 'ed25519'
UNLOCKHASH_TYPE = 'unlockhash'
MINER_PAYOUT_MATURITY_WINDOW = 144
UNLOCKHASH_SIZE = 32
UNLOCKHASH_CHECKSUM_SIZE = 6
SPECIFIER_SIZE = 16
NON_SIA_SPECIFIER = 'NonSia'
ADDRESS_TYPE_SIZE = 2
WALLET_ADDRESS_TYPE = bytearray([1])
SWAP_ADDRESS_TYPE = bytearray([2])
