# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for Capacity
"""
from .Location import Location
from six import string_types

from . import client_support


class Capacity(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type cru: float
        :type farmer: string_types
        :type hru: float
        :type location: Location
        :type mru: float
        :type node_id: string_types
        :type os_version: string_types
        :type robot_address: string_types
        :type sru: float
        :rtype: Capacity
        """

        return Capacity(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'Capacity'
        data = json or kwargs

        # set attributes
        data_types = [float]
        self.cru = client_support.set_property('cru', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.farmer = client_support.set_property('farmer', data, data_types, False, [], False, False, class_name)
        data_types = [float]
        self.hru = client_support.set_property('hru', data, data_types, False, [], False, True, class_name)
        data_types = [Location]
        self.location = client_support.set_property('location', data, data_types, False, [], False, False, class_name)
        data_types = [float]
        self.mru = client_support.set_property('mru', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.node_id = client_support.set_property('node_id', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.os_version = client_support.set_property(
            'os_version', data, data_types, False, [], False, True, class_name)
        data_types = [string_types]
        self.robot_address = client_support.set_property(
            'robot_address', data, data_types, False, [], False, True, class_name)
        data_types = [float]
        self.sru = client_support.set_property('sru', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
