# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
from . import handlers


nodes_api = Blueprint('nodes_api', __name__)


@nodes_api.route('/api/nodes', methods=['GET'])
def ListCapacity():
    """
    List all the nodes capacity
    It is handler for GET /nodes
    """
    return handlers.ListCapacityHandler()


@nodes_api.route('/api/nodes', methods=['POST'])
def RegisterCapacity():
    """
    Register a node capacity
    It is handler for POST /nodes
    """
    return handlers.RegisterCapacityHandler()
