# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


from .ListCapacityHandler import ListCapacityHandler
from .RegisterCapacityHandler import RegisterCapacityHandler
from .GetCapacityHandler import GetCapacityHandler
from .RegisterFarmerHandler import RegisterFarmerHandler
from .ListFarmersHandler import ListFarmersHandler
