#!/usr/bin/env node

// var transformer = require('api-spec-transformer');
var transformer = require(os.homedir()+'/opt/var/nodejs_modules/node_modules/api-spec-transformer');

var ramlToSwagger = new transformer.Converter(transformer.Formats.RAML10, transformer.Formats.SWAGGER);

ramlToSwagger.loadFile('main.yaml', function(err) {
  if (err) {
    console.log(err.stack);
    return;
  }

  swaggerToRaml.convert('yaml')
  .then(function(convertedData) {
    // convertedData is a raml YAML string
  //   console.log(convertedData)
    fs.writeFile("../generated/api.yaml",convertedData, function(err) {
      if(err) {
          return console.log(err);
      }
    }  )  
  })
  .catch(function(err){
    console.log(err);
  });



});