# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class MarkdownService:
    def __init__(self, client):
        self.client = client

    def renderMarkdownRaw(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Render raw markdown as HTML
        It is method for POST /markdown/raw
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/markdown/raw"
        return self.client.post(uri, data, headers, query_params, content_type)

    def renderMarkdown(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Render a markdown document as HTML
        It is method for POST /markdown
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/markdown"
        return self.client.post(uri, data, headers, query_params, content_type)
